# Configuation for robot odometry EKF
# true = fuse that measurement into the EKF
# false = ignore that measurement
frequency: 50

odom0: /jackal_velocity_controller/odom
odom0_config: [false, false, false, # x, y, z position
               false, false, false, # roll, pitch, yaw orientation
               true, true, true,    # vx, vy, vz linear velocity
               false, false, true,  # vroll, vpitch, vyaw angular velocity
               false, false, false] # ax, ay, az linear acceleration
odom0_differential: false

imu0: /imu/data
imu0_config: [false, false, false,  # x, y, z position
              true, true, true,     # roll, pitch, yaw orientation
              false, false, false,  # vx, vy, vz linear velocity
              true, true, true,     # vroll, vpitch, vyaw angular velocity
              false, false, false]  # ax, ay, az linear acceleration
imu0_differential: false

odom_frame: odom
base_link_frame: base_link
world_frame: odom

predict_to_current_time: true
